# ARGUMENTS --------------------------------------------------------------------
##
# Base Container version
# Using Flutter v3.27.x
##
ARG SDK_BASE_VERSION=SDK
##
# Base container version
##
ARG BASE_VERSION=SDK

##
# Board architecture
##
ARG IMAGE_ARCH=

##
# Board GPU vendor prefix
##
ARG GPU=

##
# Directory of the application inside container
##
ARG APP_ROOT=

# BUILD ------------------------------------------------------------------------
# TODO: cross compile x86 to arm
# We will use emulation here
##
# Build Step
##
FROM --platform=linux/${IMAGE_ARCH} \
    crossware.app:5050/public-repos/flutter:${SDK_BASE_VERSION}

ARG IMAGE_ARCH
ARG GPU
ARG APP_ROOT

WORKDIR ${APP_ROOT}
