version: "3.9"
services:
  __container__-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
      - ${DEBUG_PORT1}:${DEBUG_PORT1}

  __container__:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/__container__:${TAG}
