version: "3.9"
services:
    __container__-debug:
        build:
            context: .
            dockerfile: Dockerfile.debug
        image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
        ports:
            - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
        device_cgroup_rules:
            # Add device access rights through cgroup
            - "c 4:* rmw" # For tty
            - "c 13:* rmw" # For /dev/input devices
            - "c 226:* rmw" # For /dev/dri devices
            - "c 199:* rmw"
            - "c 29:* rmw" # For /dev/fb0
        volumes:
            - type: bind
              source: /dev
              target: /dev

    __container__:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${DOCKER_LOGIN}/__container__:${TAG}
        device_cgroup_rules:
            # Add device access rights through cgroup
            # For tty
            - "c 4:* rmw"
            # For /dev/input devices
            - "c 13:* rmw"
            # For /dev/dri devices
            - "c 226:* rmw"
            - "c 199:* rmw"
              # For /dev/fb0
            - "c 29:* rmw"
        volumes:
            - type: bind
              source: /dev
              target: /dev
