ARG BRANCH=dev
ARG UID=1000


FROM torizonextras/torizon-dev-tasks:${BRANCH}

ARG BRANCH
ARG UID

USER root

# we need to install all the ApolloX dependencies
# powershell wget git curl is already installed in the base image
RUN apt-get update && \
    apt-get install -y \
    jq \
    sudo \
# extension tools
    iputils-ping \
    dnsutils \
    nmap \
    avahi-utils \
    file sshpass \
    net-tools \
    iproute2 \
    iptables \
    kmod \
# extension tools
# graphical tools
    wayland-protocols \
    libwayland-dev \
    libwayland-egl-backend-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libncursesw5-dev \
    libncursesw6 \
# graphical tools
    && \
    apt-get clean && apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# set the iptables legacy
RUN update-alternatives --set iptables /usr/sbin/iptables-legacy && \
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

# we also need to install nodejs 20
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# to share the graphical interface with the host
ENV WAYLAND_DISPLAY=wayland-0
ENV DISPLAY=:0
ENV XDG_RUNTIME_DIR=/run/user/${UID}
ENV XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop

VOLUME /tmp/.X11-unix:/tmp/.X11-unix
VOLUME /run/user/${UID}/wayland-0:/run/user/${UID}/wayland-0
# # Set the Wayland socket file permissions
# RUN chmod 777 /run/user/${UID}/wayland-0

# to share the docker socket with the host
VOLUME /var/run/docker.sock:/var/run/docker.sock

# use docker daemon and tools
COPY --from=docker:dind /usr/local/bin/containerd /usr/local/bin/
COPY --from=docker:dind /usr/local/bin/runc /usr/local/bin/
COPY --from=docker:dind /usr/local/bin/dockerd /usr/local/bin/
COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/
COPY --from=docker:dind /usr/local/bin/docker-init /usr/local/bin/
COPY --from=docker:dind /usr/local/bin/docker-proxy /usr/local/bin/
COPY --from=docker:dind /usr/local/bin/containerd-shim-runc-v2 /usr/local/bin/
COPY --from=docker:dind /usr/local/libexec/docker/cli-plugins /usr/local/lib/docker/cli-plugins

# get current scripts
WORKDIR /home/torizon/.apollox/scripts/node
RUN chmod -R 757 /root && \
    npm install ./apollox-0.2.1.tgz

# inject the zygote
COPY ./zygote.xsh /home/torizon/.apollox/scripts/zygote.xsh
RUN chmod +x /home/torizon/.apollox/scripts/zygote.xsh && \
    ln -s /home/torizon/.apollox/scripts/zygote.xsh /usr/local/bin/zygote

USER torizon

# the workspace will be the mount point for local path
WORKDIR /workspace

CMD [ "xonsh" ]
