# Copyright (c) 2025 Toradex
# SPDX-License-Identifier: MIT

ARG BRANCH=dev

FROM debian:bookworm-slim

# install the dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    sudo \
    python3 \
    python3-pip \
    python3-setuptools \
    pipx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add a very different user id to avoid conflicts with the host user
RUN useradd -l -m -u 1010 torizon && \
    usermod -aG sudo torizon && \
    echo "torizon ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# setup xonsh
COPY ./bash/setup-xonsh.sh /root/setup-xonsh.sh
RUN chmod +x /root/setup-xonsh.sh && \
    touch /home/torizon/.xonshrc && \
    PSSWD=noempty /root/setup-xonsh.sh && \
    ln -s /root/.local/bin/xonsh /usr/local/bin/xonsh && \
    mkdir -p /home/torizon/.local/bin && \
    ln -s /root/.local/bin/xonsh /home/torizon/.local/bin/xonsh

# Switch to the Torizon user
USER torizon

ENTRYPOINT [ "/root/.local/bin/xonsh" ]

CMD [ "--help" ]
