name: Secret Scan
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_call:

jobs:
  trufflehog:
    runs-on: ubuntu-24.04
    name: TruffleHog Secret Scan
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: TruffleHog Scan Workspace Files
        shell: bash
        run: |
          docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem \
            /pwd \
            --exclude-paths=/pwd/.exclude-truffle \
            --fail
